version: '3'
services:
  mongo:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=planning-poker
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /planning-poker/mongo:/data/db
    ports:
      - '27017:27017'

  sonarqube:
    ports:
      - "9000:9000"
    image: sonarqube:8.3-community

  mongo-test:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=planning-poker-test
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27018:27017"
